name: Deploy VPN
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Deployment Script
        run: echo 'This simulates a VPN deployment.'
